org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.13
#
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.221
neo_version_range=[21.1.0,)
loader_version_range=[4,)
#
guideme_version = 21.1.0
guideme_version_range = [20.0.0,)
#
jei_minecraft=1.21.1
jei_version=19.25.0.325
#

## Mod Properties

mod_id=synergy
mod_name=Synergy
mod_license=Custom License
mod_version=0.8.4-hotfix1
mod_group_id=com.devdyna.synergy
mod_authors=DevDyna
mod_description=A bunch of Magic-Tech and fun made gadgets


ponder_version_range=[1.0.81+mc1.21.1, 1.1.0+mc1.21.1]
ponder_version = 1.0.82

flywheel_version_range=[1.0.6, 1.1.0]
flywheel_version = 1.0.6