org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.13
#
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.194
neo_version_range=[21.1.0,)
loader_version_range=[4,)
#
guideme_version = 21.1.0
guideme_version_range = [20.0.0,)
#
jei_minecraft=1.21.1
jei_version=19.21.0.247
#

## Mod Properties

mod_id=synergy
mod_name=Synergy
mod_license=MIT
mod_version=0.3
mod_group_id=com.devdyna.synergy
mod_authors=DevDyna
mod_description=todo
